### ISSUE TITLE
First run of documenso docker installation

### ISSUE THREAD

**Issue by philxws692** [documenso/documenso#1390]
### Issue Description

When trying to login to the given admin account or creating a new account I am confronted with the error:
<img width="366" alt="image" src="https://github.com/user-attachments/assets/43c1edef-9f39-45ba-92ab-5e6163e3fc94">

In the logs of the docker container I am welcomed by this message
```
PrismaClientKnownRequestError: 
Invalid `prisma.user.findFirst()` invocation:
The table `public.User` does not exist in the current database.
    at Cn.handleRequestError (/app/node_modules/@prisma/client/runtime/library.js:123:6817)
    at Cn.handleAndLogRequestError (/app/node_modules/@prisma/client/runtime/library.js:123:6206)
    at Cn.request (/app/node_modules/@prisma/client/runtime/library.js:123:5926)
    at async l (/app/node_modules/@prisma/client/runtime/library.js:128:9968)
    at async h (/app/apps/web/.next/server/pages/api/trpc/[trpc].js:1:113665)
    at async /app/apps/web/.next/server/pages/api/trpc/[trpc].js:1:128962
    at async resolveMiddleware (file:///app/node_modules/@trpc/server/dist/index.mjs:420:30)
    at async callRecursive (file:///app/node_modules/@trpc/server/dist/index.mjs:456:32)
    at async callRecursive (file:///app/node_modules/@trpc/server/dist/index.mjs:456:32)
    at async resolve (file:///app/node_modules/@trpc/server/dist/index.mjs:486:24) {
  code: 'P2021',
  clientVersion: '5.4.2',
  meta: { table: 'public.User' }
}
```
Also when I check the database container there are no relations, so it seems like the database is not initialized/setup'ed correctly

### Steps to Reproduce

1. Setup a `docker-compose.yml`
```yml
services:
  app:
    image: documenso/documenso:latest
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/documenso
      - NEXTAUTH_URL=https://sign.example.de
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - NEXT_PRIVATE_ENCRYPTION_KEY=${NEXT_PRIVATE_ENCRYPTION_KEY}
      - NEXT_PRIVATE_ENCRYPTION_SECONDARY_KEY=${NEXT_PRIVATE_ENCRYPTION_SECONDARY_KEY}
      - NEXT_PUBLIC_WEBAPP_URL=https://sign.example.de
    ports:
      - "3002:3000"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=documenso
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
```
2. Start the containers
3. Try to login or create an account

### Expected Behavior

That I am able to login or create an account

### Current Behavior

Not working

### Operating System [e.g., Windows 10]

Ubuntu 22.04 LTS

### Browser [e.g., Chrome, Firefox]

Brave

### Version [e.g., 2.0.1]

latest

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [X] I have included relevant environment information.
- [X] I have included any relevant screenshots.
- [X] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [ ] I want to work on creating a PR for this issue if approved
