### ISSUE TITLE
does not receive verification email

### ISSUE THREAD

**Issue by fred781987** [documenso/documenso#1422]
### Issue Description

I am trying to create an account on documenso but it does not send verification email on my email can someone help me out ?

### Please check the boxes that apply to this issue report.

- [ ] I have searched the existing issues to make sure this is not a duplicate.
- [ ] I have provided steps to reproduce the issue.
- [ ] I have included relevant environment information.
- [ ] I have included any relevant screenshots.
- [ ] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [ ] I want to work on creating a PR for this issue if approved

**Comment by dguyen** [comment]
Hi, are you self hosting Documenso? Or is this happening on app.documenso.com?

**Comment by Anshsahu0802** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by syedfaiqyazdani** [comment]
i have setup documenso locally when i try to create an account i don't receive any email for verfication any solution to solve this problem

**Comment by pbmagnet4** [comment]
I am experiencing the same issue. Locally hosted following this tutorial:

https://mariushosting.com/how-to-install-documenso-on-your-synology-nas/

My guess is that there is an issue with setting up the STMP protocol. Any help on the matter would be greatly appreciated.

**Comment by PhatWheZ** [comment]
@dguyen I am trying to setup a self-hosted environment and when running the logs output failed smtp messages, but if you try again after a few seconds it shows to send, but nothing comes through

I am keen to assist in providing to the community where i can, as this is a great project!

**Comment by candiepih** [comment]
I am currently experiencing this problem. It's sending reset password emails but not email verification emails

**Comment by PhatWheZ** [comment]
@candiepih sounds odd that half works and not the rest.
On my end, i have mails working no problem with the following variables declared in a `.env` file with only `env_file: .env` being listed in my `docker-compose.yml` file
```
# [[SMTP]]
NEXT_PRIVATE_SMTP_TRANSPORT="smtp-auth"
NEXT_PRIVATE_SMTP_HOST="{Host FQDN or IP}"
NEXT_PRIVATE_SMTP_PORT="25"
NEXT_PRIVATE_SMTP_USERNAME="documenso@domain.io"
NEXT_PRIVATE_SMTP_PASSWORD="app-password"
NEXT_PRIVATE_SMTP_SECURE="false"
NEXT_PRIVATE_SMTP_UNSAFE_IGNORE_TLS="true"
NEXT_PRIVATE_SMTP_FROM_NAME="Documenso"
NEXT_PRIVATE_SMTP_FROM_ADDRESS="documenso@{yourdomain.com}"
NEXT_PUBLIC_DOCUMENT_SIZE_UPLOAD_LIMIT=50
```

**Comment by candiepih** [comment]
> @candiepih sounds odd that half works and not the rest. On my end, i have mails working no problem with the following variables declared in a `.env` file with only `env_file: .env` being listed in my `docker-compose.yml` file
> 
> ```
> # [[SMTP]]
> NEXT_PRIVATE_SMTP_TRANSPORT="smtp-auth"
> NEXT_PRIVATE_SMTP_HOST="{Host FQDN or IP}"
> NEXT_PRIVATE_SMTP_PORT="25"
> NEXT_PRIVATE_SMTP_USERNAME="documenso@domain.io"
> NEXT_PRIVATE_SMTP_PASSWORD="app-password"
> NEXT_PRIVATE_SMTP_SECURE="false"
> NEXT_PRIVATE_SMTP_UNSAFE_IGNORE_TLS="true"
> NEXT_PRIVATE_SMTP_FROM_NAME="Documenso"
> NEXT_PRIVATE_SMTP_FROM_ADDRESS="documenso@{yourdomain.com}"
> NEXT_PUBLIC_DOCUMENT_SIZE_UPLOAD_LIMIT=50
> ```

I was using docker-compose before and had that issue, it's now working after I cloned the repo. Maybe the issue lies within the code associated with the Docker image.

**Comment by PhatWheZ** [comment]
I setup my own `docker-compose.yml` file which works fine. I didnt copy the repo as I am trying to find the kinks.
```
services:
  postgres:
    image: postgres:15
    container_name: postgres
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER}']
      interval: 10s
      timeout: 5s
      retries: 5
    env_file: .env
    volumes:
      - postgres:/var/lib/postgresql/data

  documenso:
    image: documenso/documenso:latest
    container_name: documenso
    depends_on:
      postgres:
        condition: service_healthy
    env_file: .env
    environment:
      - NEXT_PRIVATE_SIGNING_PASSPHRASE=${NEXT_PRIVATE_SIGNING_PASSPRHASE}
    volumes:
      - /opt/documenso/cert.p12:/opt/documenso/cert.p12
    ports:
      - 3000:3000

volumes:
  postgres:
```
