### ISSUE TITLE
Task failed Error: Failed to get private key bags

### ISSUE THREAD

**Issue by InvixGG** [documenso/documenso#1457]
### Issue Description

I'm trying to setup Documenso on a Raspberry Pi 5 in a docker container. I've tried everything but I'm unable to get rid of this error.

Everything works, signup, sending confirmation email, uploading documents, signing documents, but the sealing documents part is where it all goes wrong. I have no idea anymore what's the issue.

### Steps to Reproduce

I do this on my Windows pc:
`openssl genrsa -out private.key 2048`
`openssl req -new -x509 -key private.key -out certificate.crt -days 365`
`openssl pkcs12 -export -out certificate.p12 -inkey private.key -in certificate.crt -legacy`
`[Convert]::ToBase64String([IO.File]::ReadAllBytes("D:\Documents\Invix Digital\Companies\Vexel Studios\Docker Containers\Documenso\certificate.p12")) | Set-Clipboard`

.env:
```env
NEXTAUTH_SECRET=mysecret
NEXT_PRIVATE_ENCRYPTION_KEY=mykey
NEXT_PRIVATE_ENCRYPTION_SECONDARY_KEY=mykeysecondary
NEXT_PUBLIC_WEBAPP_URL=mydomain
NEXT_PRIVATE_INTERNAL_WEBAPP_URL=myraspberrylocalip

# SMTP Configuration
NEXT_PRIVATE_SMTP_TRANSPORT="smtp-auth"
NEXT_PRIVATE_SMTP_HOST="mymailhost"
NEXT_PRIVATE_SMTP_PORT=465
NEXT_PRIVATE_SMTP_USERNAME="myusername"
NEXT_PRIVATE_SMTP_PASSWORD="mypassword"
NEXT_PRIVATE_SMTP_FROM_NAME="myname"
NEXT_PRIVATE_SMTP_FROM_ADDRESS="myaddress"
NEXT_PRIVATE_SMTP_SECURE="true"
NEXT_PRIVATE_SMTP_UNSAFE_IGNORE_TLS="false"

NEXT_PUBLIC_DOCUMENT_SIZE_UPLOAD_LIMIT=50

PORT=3001

POSTGRES_USER=postgres
POSTGRES_PASSWORD=mypassword
POSTGRES_DB=postgres

NEXT_PRIVATE_DATABASE_URL="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@documenso-database-1:5432/${POSTGRES_DB}"
NEXT_PRIVATE_JOBS_PROVIDER="local"
NEXT_PRIVATE_SIGNING_LOCAL_FILE_PATH="/opt/documenso/cert.p12"
NEXT_PRIVATE_SIGNING_PASSPHRASE=mypassword
NEXT_PRIVATE_SIGNING_LOCAL_FILE_CONTENTS=mybase64
```

docker-compose.yml:
```yml
name: documenso

services:
  database:
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER:?err}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?err}
      - POSTGRES_DB=${POSTGRES_DB:?err}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER}']
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5435:5432"
    volumes:
      - database:/var/lib/postgresql/data

  documenso:
    image: documenso/documenso:latest
    user: "root"
    depends_on:
      database:
        condition: service_healthy
    environment:
      - PORT=${PORT:-3000}
      - NEXTAUTH_URL=${NEXTAUTH_URL:-${NEXT_PUBLIC_WEBAPP_URL}}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:?err}
      - NEXT_PRIVATE_ENCRYPTION_KEY=${NEXT_PRIVATE_ENCRYPTION_KEY:?err}
      - NEXT_PRIVATE_ENCRYPTION_SECONDARY_KEY=${NEXT_PRIVATE_ENCRYPTION_SECONDARY_KEY:?err}
      - NEXT_PRIVATE_GOOGLE_CLIENT_ID=${NEXT_PRIVATE_GOOGLE_CLIENT_ID}
      - NEXT_PRIVATE_GOOGLE_CLIENT_SECRET=${NEXT_PRIVATE_GOOGLE_CLIENT_SECRET}
      - NEXT_PUBLIC_WEBAPP_URL=${NEXT_PUBLIC_WEBAPP_URL:?err}
      - NEXT_PRIVATE_INTERNAL_WEBAPP_URL=${NEXT_PRIVATE_INTERNAL_WEBAPP_URL:-http://localhost:$PORT}
      - NEXT_PUBLIC_MARKETING_URL=${NEXT_PUBLIC_MARKETING_URL:-https://documenso.com}
      - NEXT_PRIVATE_DATABASE_URL=${NEXT_PRIVATE_DATABASE_URL:?err}
      - NEXT_PRIVATE_DIRECT_DATABASE_URL=${NEXT_PRIVATE_DIRECT_DATABASE_URL:-${NEXT_PRIVATE_DATABASE_URL}}
      - NEXT_PUBLIC_UPLOAD_TRANSPORT=${NEXT_PUBLIC_UPLOAD_TRANSPORT:-database}
      - NEXT_PRIVATE_UPLOAD_ENDPOINT=${NEXT_PRIVATE_UPLOAD_ENDPOINT}
      - NEXT_PRIVATE_UPLOAD_FORCE_PATH_STYLE=${NEXT_PRIVATE_UPLOAD_FORCE_PATH_STYLE}
      - NEXT_PRIVATE_UPLOAD_REGION=${NEXT_PRIVATE_UPLOAD_REGION}
      - NEXT_PRIVATE_UPLOAD_BUCKET=${NEXT_PRIVATE_UPLOAD_BUCKET}
      - NEXT_PRIVATE_UPLOAD_ACCESS_KEY_ID=${NEXT_PRIVATE_UPLOAD_ACCESS_KEY_ID}
      - NEXT_PRIVATE_UPLOAD_SECRET_ACCESS_KEY=${NEXT_PRIVATE_UPLOAD_SECRET_ACCESS_KEY}
      - NEXT_PRIVATE_SMTP_TRANSPORT=${NEXT_PRIVATE_SMTP_TRANSPORT:?err}
      - NEXT_PRIVATE_SMTP_HOST=${NEXT_PRIVATE_SMTP_HOST}
      - NEXT_PRIVATE_SMTP_PORT=${NEXT_PRIVATE_SMTP_PORT}
      - NEXT_PRIVATE_SMTP_USERNAME=${NEXT_PRIVATE_SMTP_USERNAME}
      - NEXT_PRIVATE_SMTP_PASSWORD=${NEXT_PRIVATE_SMTP_PASSWORD}
      - NEXT_PRIVATE_SMTP_APIKEY_USER=${NEXT_PRIVATE_SMTP_APIKEY_USER}
      - NEXT_PRIVATE_SMTP_APIKEY=${NEXT_PRIVATE_SMTP_APIKEY}
      - NEXT_PRIVATE_SMTP_SECURE=${NEXT_PRIVATE_SMTP_SECURE}
      - NEXT_PRIVATE_SMTP_FROM_NAME=${NEXT_PRIVATE_SMTP_FROM_NAME:?err}
      - NEXT_PRIVATE_SMTP_FROM_ADDRESS=${NEXT_PRIVATE_SMTP_FROM_ADDRESS:?err}
      - NEXT_PRIVATE_RESEND_API_KEY=${NEXT_PRIVATE_RESEND_API_KEY}
      - NEXT_PRIVATE_MAILCHANNELS_API_KEY=${NEXT_PRIVATE_MAILCHANNELS_API_KEY}
      - NEXT_PRIVATE_MAILCHANNELS_ENDPOINT=${NEXT_PRIVATE_MAILCHANNELS_ENDPOINT}
      - NEXT_PRIVATE_MAILCHANNELS_DKIM_DOMAIN=${NEXT_PRIVATE_MAILCHANNELS_DKIM_DOMAIN}
      - NEXT_PRIVATE_MAILCHANNELS_DKIM_SELECTOR=${NEXT_PRIVATE_MAILCHANNELS_DKIM_SELECTOR}
      - NEXT_PRIVATE_MAILCHANNELS_DKIM_PRIVATE_KEY=${NEXT_PRIVATE_MAILCHANNELS_DKIM_PRIVATE_KEY}
      - NEXT_PUBLIC_DOCUMENT_SIZE_UPLOAD_LIMIT=${NEXT_PUBLIC_DOCUMENT_SIZE_UPLOAD_LIMIT}
      - NEXT_PUBLIC_POSTHOG_KEY=${NEXT_PUBLIC_POSTHOG_KEY}
      - NEXT_PUBLIC_DISABLE_SIGNUP=${NEXT_PUBLIC_DISABLE_SIGNUP}
      - NEXT_PRIVATE_SIGNING_LOCAL_FILE_PATH=${NEXT_PRIVATE_SIGNING_LOCAL_FILE_PATH:-/opt/documenso/cert.p12}
      - NEXT_PRIVATE_SIGNING_PASSPHRASE=${NEXT_PRIVATE_SIGNING_PASSPHRASE}
      - NEXT_PRIVATE_SIGNING_LOCAL_FILE_CONTENTS=${NEXT_PRIVATE_SIGNING_LOCAL_FILE_CONTENTS}
    ports:
      - ${PORT:-3000}:${PORT:-3000}
    volumes:
      - /home/Levi/documenso/certificate.p12:/opt/documenso/cert.p12

volumes:
  database:
```

Then I send over all files from my pc to my PI:
`scp .env certificate.p12 documenso-docker-compose.yml Levi@myraspberrypiip:/home/Levi/documenso/`

On my PI I do this:
`sudo chown 1001 ./documenso/certificate.p12`

And then I start up the containers:
`sudo docker compose -f ./documenso/documenso-docker-compose.yml --env-file ./documenso/.env up -d --force-recreate --pull=always`

### Expected Behavior

It should seal the documents.

### Current Behavior

We get this error:
```
Submitting job to endpoint: http://myraspberrypiip:3001/api/jobs/internal.seal-document/cm3c3m74q001qke29bw30zzur
[JOBS]: Triggering job internal.seal-document with payload {
  documentId: 1,
  requestMetadata: {
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36'
  }
}
[JOBS:task-06292354c47ced55f2e4d03bfb7e63bc9b46a8180d6f46eb02d23d3ebb8b8a45--cm3c3m74q001qke29bw30zzur] Task failed Error: Failed to get private key bags
    at I (/app/apps/web/.next/server/chunks/9182.js:1:1179113)
    at async I (/app/apps/web/.next/server/chunks/9182.js:1:1177177)
    at async /app/apps/web/.next/server/chunks/9783.js:1:29693
    at async Object.runTask (/app/apps/web/.next/server/chunks/9783.js:1:18663)
    at async Object.handler (/app/apps/web/.next/server/chunks/9783.js:1:29399)
    at async /app/apps/web/.next/server/chunks/9783.js:1:17053
    at async K (/app/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:16853)
    at async U.render (/app/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:17492)
    at async NextNodeServer.runApi (/app/node_modules/next/dist/server/next-server.js:600:9)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/next/dist/server/next-server.js:269:37) {
  code: 'GenericFailure'
}
[JOBS]: Job internal.seal-document failed b [BackgroundTaskFailedError]: Task failed
    at Object.runTask (/app/apps/web/.next/server/chunks/9783.js:1:19040)
    at async Object.handler (/app/apps/web/.next/server/chunks/9783.js:1:29399)
    at async /app/apps/web/.next/server/chunks/9783.js:1:17053
    at async K (/app/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:16853)
    at async U.render (/app/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:17492)
    at async NextNodeServer.runApi (/app/node_modules/next/dist/server/next-server.js:600:9)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/next/dist/server/next-server.js:269:37)
    at async NextNodeServer.handleRequestImpl (/app/node_modules/next/dist/server/base-server.js:816:17)
    at async invokeRender (/app/node_modules/next/dist/server/lib/router-server.js:174:21)
    at async handleRequest (/app/node_modules/next/dist/server/lib/router-server.js:353:24)
Submitting job to endpoint: http://myraspberrypiip:3001/api/jobs/internal.seal-document/cm3c3m74q001qke29bw30zzur
[JOBS]: Triggering job internal.seal-document with payload {
  documentId: 1,
  requestMetadata: {
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36'
  }
}
[JOBS:task-06292354c47ced55f2e4d03bfb7e63bc9b46a8180d6f46eb02d23d3ebb8b8a45--cm3c3m74q001qke29bw30zzur] Task failed Error: Failed to get private key bags
    at I (/app/apps/web/.next/server/chunks/9182.js:1:1179113)
    at async I (/app/apps/web/.next/server/chunks/9182.js:1:1177177)
    at async /app/apps/web/.next/server/chunks/9783.js:1:29693
    at async Object.runTask (/app/apps/web/.next/server/chunks/9783.js:1:18663)
    at async Object.handler (/app/apps/web/.next/server/chunks/9783.js:1:29399)
    at async /app/apps/web/.next/server/chunks/9783.js:1:17053
    at async K (/app/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:16853)
    at async U.render (/app/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:17492)
    at async NextNodeServer.runApi (/app/node_modules/next/dist/server/next-server.js:600:9)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/next/dist/server/next-server.js:269:37) {
  code: 'GenericFailure'
}
[JOBS]: Job internal.seal-document failed b [BackgroundTaskFailedError]: Task failed
    at Object.runTask (/app/apps/web/.next/server/chunks/9783.js:1:19040)
    at async Object.handler (/app/apps/web/.next/server/chunks/9783.js:1:29399)
    at async /app/apps/web/.next/server/chunks/9783.js:1:17053
    at async K (/app/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:16853)
    at async U.render (/app/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:17492)
    at async NextNodeServer.runApi (/app/node_modules/next/dist/server/next-server.js:600:9)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/next/dist/server/next-server.js:269:37)
    at async NextNodeServer.handleRequestImpl (/app/node_modules/next/dist/server/base-server.js:816:17)
    at async invokeRender (/app/node_modules/next/dist/server/lib/router-server.js:174:21)
    at async handleRequest (/app/node_modules/next/dist/server/lib/router-server.js:353:24)
Submitting job to endpoint: http://myraspberrypiip:3001/api/jobs/internal.seal-document/cm3c3m74q001qke29bw30zzur
[JOBS]: Triggering job internal.seal-document with payload {
  documentId: 1,
  requestMetadata: {
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36'
  }
}
[JOBS:task-06292354c47ced55f2e4d03bfb7e63bc9b46a8180d6f46eb02d23d3ebb8b8a45--cm3c3m74q001qke29bw30zzur] Task failed Error: Failed to get private key bags
    at I (/app/apps/web/.next/server/chunks/9182.js:1:1179113)
    at async I (/app/apps/web/.next/server/chunks/9182.js:1:1177177)
    at async /app/apps/web/.next/server/chunks/9783.js:1:29693
    at async Object.runTask (/app/apps/web/.next/server/chunks/9783.js:1:18663)
    at async Object.handler (/app/apps/web/.next/server/chunks/9783.js:1:29399)
    at async /app/apps/web/.next/server/chunks/9783.js:1:17053
    at async K (/app/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:16853)
    at async U.render (/app/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:17492)
    at async NextNodeServer.runApi (/app/node_modules/next/dist/server/next-server.js:600:9)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/next/dist/server/next-server.js:269:37) {
  code: 'GenericFailure'
}
[JOBS]: Job internal.seal-document failed b [BackgroundTaskFailedError]: Task failed
    at Object.runTask (/app/apps/web/.next/server/chunks/9783.js:1:19040)
    at async Object.handler (/app/apps/web/.next/server/chunks/9783.js:1:29399)
    at async /app/apps/web/.next/server/chunks/9783.js:1:17053
    at async K (/app/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:16853)
    at async U.render (/app/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:17492)
    at async NextNodeServer.runApi (/app/node_modules/next/dist/server/next-server.js:600:9)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/next/dist/server/next-server.js:269:37)
    at async NextNodeServer.handleRequestImpl (/app/node_modules/next/dist/server/base-server.js:816:17)
    at async invokeRender (/app/node_modules/next/dist/server/lib/router-server.js:174:21)
    at async handleRequest (/app/node_modules/next/dist/server/lib/router-server.js:353:24)
Submitting job to endpoint: http://myraspberrypiip:3001/api/jobs/internal.seal-document/cm3c3m74q001qke29bw30zzur
[JOBS]: Triggering job internal.seal-document with payload {
  documentId: 1,
  requestMetadata: {
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36'
  }
}
[JOBS]: Job internal.seal-document failed p [BackgroundTaskExceededRetriesError]: Task exceeded retries
    at Object.runTask (/app/apps/web/.next/server/chunks/9783.js:1:18622)
    at async Object.handler (/app/apps/web/.next/server/chunks/9783.js:1:29399)
    at async /app/apps/web/.next/server/chunks/9783.js:1:17053
    at async K (/app/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:16853)
    at async U.render (/app/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:17492)
    at async NextNodeServer.runApi (/app/node_modules/next/dist/server/next-server.js:600:9)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/next/dist/server/next-server.js:269:37)
    at async NextNodeServer.handleRequestImpl (/app/node_modules/next/dist/server/base-server.js:816:17)
    at async invokeRender (/app/node_modules/next/dist/server/lib/router-server.js:174:21)
    at async handleRequest (/app/node_modules/next/dist/server/lib/router-server.js:353:24)
```

### Operating System [e.g., Windows 10]

Windows 11

### Browser [e.g., Chrome, Firefox]

Vivaldi (Chromium based)

### Version [e.g., 2.0.1]

latest

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [X] I have included relevant environment information.
- [ ] I have included any relevant screenshots.
- [X] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [ ] I want to work on creating a PR for this issue if approved
