### ISSUE TITLE
Issue can't reach database server

### ISSUE THREAD

**Issue by doronkatz** [documenso/documenso#1624]
Hi folks,

Just installed via docker Documenso but getting the following docker log errors:
```
❯ docker-compose up
WARN[0000] The "PORT" variable is not set. Defaulting to a blank string. 
[+] Running 2/0
 ✔ Container documenso-production-database-1   Created                                                                                    0.0s 
 ✔ Container documenso-production-documenso-1  Created                                                                                    0.0s 
Attaching to database-1, documenso-1
database-1   | 
database-1   | PostgreSQL Database directory appears to contain a database; Skipping initialization
database-1   | 
database-1   | 2025-02-02 19:41:42.352 UTC [1] LOG:  starting PostgreSQL 15.10 (Debian 15.10-1.pgdg120+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
database-1   | 2025-02-02 19:41:42.352 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
database-1   | 2025-02-02 19:41:42.352 UTC [1] LOG:  listening on IPv6 address "::", port 5432
database-1   | 2025-02-02 19:41:42.353 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
database-1   | 2025-02-02 19:41:42.356 UTC [29] LOG:  database system was interrupted; last known up at 2025-01-21 00:54:36 UTC
database-1   | 2025-02-02 19:41:42.391 UTC [29] LOG:  database system was not properly shut down; automatic recovery in progress
database-1   | 2025-02-02 19:41:42.392 UTC [29] LOG:  redo starts at 0/1960260
database-1   | 2025-02-02 19:41:42.392 UTC [29] LOG:  invalid record length at 0/1960348: wanted 24, got 0
database-1   | 2025-02-02 19:41:42.392 UTC [29] LOG:  redo done at 0/1960310 system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.00 s
database-1   | 2025-02-02 19:41:42.393 UTC [27] LOG:  checkpoint starting: end-of-recovery immediate wait
database-1   | 2025-02-02 19:41:42.396 UTC [27] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.001 s, sync=0.001 s, total=0.004 s; sync files=2, longest=0.001 s, average=0.001 s; distance=0 kB, estimate=0 kB
database-1   | 2025-02-02 19:41:42.401 UTC [1] LOG:  database system is ready to accept connections
database-1   | 2025-02-02 19:41:52.335 UTC [40] FATAL:  role "documenso" does not exist
documenso-1  | + npx prisma migrate deploy --schema ./packages/prisma/schema.prisma
documenso-1  | Prisma schema loaded from packages/prisma/schema.prisma
documenso-1  | Datasource "db": PostgreSQL database "documenso", schema "public" at "127.0.0.1:5432"
documenso-1  | 
documenso-1  | Error: P1001: Can't reach database server at `127.0.0.1`:`5432`
documenso-1  | 
documenso-1  | Please make sure your database server is running at `127.0.0.1`:`5432`.
documenso-1  | npm notice
documenso-1  | npm notice New major version of npm available! 10.7.0 -> 11.1.0
documenso-1  | npm notice Changelog: https://github.com/npm/cli/releases/tag/v11.1.0
documenso-1  | npm notice To update run: npm install -g npm@11.1.0
documenso-1  | npm notice
documenso-1  | + node apps/web/server.js
documenso-1  |   ▲ Next.js 14.2.6
documenso-1  |   - Local:        http://46f25f589faa:3000
documenso-1  |   - Network:      http://172.23.0.3:3000
documenso-1  | 
documenso-1  |  ✓ Starting...
documenso-1  |  ✓ Ready in 50ms
database-1   | 2025-02-02 19:42:02.391 UTC [48] FATAL:  role "documenso" does not exist
database-1   | 2025-02-02 19:42:12.453 UTC [56] FATAL:  role "documenso" does not exist
```

My `compose.yml` file is as follows:
```
name: documenso-production

services:
  database:
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER:?err}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?err}
      - POSTGRES_DB=${POSTGRES_DB:?err}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER}']
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - database:/var/lib/postgresql/data

  documenso:
    image: documenso/documenso:latest
    depends_on:
      database:
        condition: service_healthy
    environment:
      - PORT=${PORT:-3000}
      - NEXTAUTH_URL=${NEXTAUTH_URL:-${NEXT_PUBLIC_WEBAPP_URL}}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:?err}
      - NEXT_PRIVATE_ENCRYPTION_KEY=${NEXT_PRIVATE_ENCRYPTION_KEY:?err}
      - NEXT_PRIVATE_ENCRYPTION_SECONDARY_KEY=${NEXT_PRIVATE_ENCRYPTION_SECONDARY_KEY:?err}
      - NEXT_PRIVATE_GOOGLE_CLIENT_ID=${NEXT_PRIVATE_GOOGLE_CLIENT_ID}
      - NEXT_PRIVATE_GOOGLE_CLIENT_SECRET=${NEXT_PRIVATE_GOOGLE_CLIENT_SECRET}
      - NEXT_PUBLIC_WEBAPP_URL=${NEXT_PUBLIC_WEBAPP_URL:?err}
      - NEXT_PRIVATE_INTERNAL_WEBAPP_URL=${NEXT_PRIVATE_INTERNAL_WEBAPP_URL:-http://localhost:$PORT}
      - NEXT_PUBLIC_MARKETING_URL=${NEXT_PUBLIC_MARKETING_URL:-https://documenso.com}
      - NEXT_PRIVATE_DATABASE_URL=${NEXT_PRIVATE_DATABASE_URL:?err}
      - NEXT_PRIVATE_DIRECT_DATABASE_URL=${NEXT_PRIVATE_DIRECT_DATABASE_URL:-${NEXT_PRIVATE_DATABASE_URL}}
      - NEXT_PUBLIC_UPLOAD_TRANSPORT=${NEXT_PUBLIC_UPLOAD_TRANSPORT:-database}
      - NEXT_PRIVATE_UPLOAD_ENDPOINT=${NEXT_PRIVATE_UPLOAD_ENDPOINT}
      - NEXT_PRIVATE_UPLOAD_FORCE_PATH_STYLE=${NEXT_PRIVATE_UPLOAD_FORCE_PATH_STYLE}
      - NEXT_PRIVATE_UPLOAD_REGION=${NEXT_PRIVATE_UPLOAD_REGION}
      - NEXT_PRIVATE_UPLOAD_BUCKET=${NEXT_PRIVATE_UPLOAD_BUCKET}
      - NEXT_PRIVATE_UPLOAD_ACCESS_KEY_ID=${NEXT_PRIVATE_UPLOAD_ACCESS_KEY_ID}
      - NEXT_PRIVATE_UPLOAD_SECRET_ACCESS_KEY=${NEXT_PRIVATE_UPLOAD_SECRET_ACCESS_KEY}
      - NEXT_PRIVATE_SMTP_TRANSPORT=${NEXT_PRIVATE_SMTP_TRANSPORT:?err}
      - NEXT_PRIVATE_SMTP_HOST=${NEXT_PRIVATE_SMTP_HOST}
      - NEXT_PRIVATE_SMTP_PORT=${NEXT_PRIVATE_SMTP_PORT}
      - NEXT_PRIVATE_SMTP_USERNAME=${NEXT_PRIVATE_SMTP_USERNAME}
      - NEXT_PRIVATE_SMTP_PASSWORD=${NEXT_PRIVATE_SMTP_PASSWORD}
      - NEXT_PRIVATE_SMTP_APIKEY_USER=${NEXT_PRIVATE_SMTP_APIKEY_USER}
      - NEXT_PRIVATE_SMTP_APIKEY=${NEXT_PRIVATE_SMTP_APIKEY}
      - NEXT_PRIVATE_SMTP_SECURE=${NEXT_PRIVATE_SMTP_SECURE}
      - NEXT_PRIVATE_SMTP_FROM_NAME=${NEXT_PRIVATE_SMTP_FROM_NAME:?err}
      - NEXT_PRIVATE_SMTP_FROM_ADDRESS=${NEXT_PRIVATE_SMTP_FROM_ADDRESS:?err}
      - NEXT_PRIVATE_SMTP_SERVICE=${NEXT_PRIVATE_SMTP_SERVICE}
      - NEXT_PRIVATE_RESEND_API_KEY=${NEXT_PRIVATE_RESEND_API_KEY}
      - NEXT_PRIVATE_MAILCHANNELS_API_KEY=${NEXT_PRIVATE_MAILCHANNELS_API_KEY}
      - NEXT_PRIVATE_MAILCHANNELS_ENDPOINT=${NEXT_PRIVATE_MAILCHANNELS_ENDPOINT}
      - NEXT_PRIVATE_MAILCHANNELS_DKIM_DOMAIN=${NEXT_PRIVATE_MAILCHANNELS_DKIM_DOMAIN}
      - NEXT_PRIVATE_MAILCHANNELS_DKIM_SELECTOR=${NEXT_PRIVATE_MAILCHANNELS_DKIM_SELECTOR}
      - NEXT_PRIVATE_MAILCHANNELS_DKIM_PRIVATE_KEY=${NEXT_PRIVATE_MAILCHANNELS_DKIM_PRIVATE_KEY}
      - NEXT_PUBLIC_DOCUMENT_SIZE_UPLOAD_LIMIT=${NEXT_PUBLIC_DOCUMENT_SIZE_UPLOAD_LIMIT}
      - NEXT_PUBLIC_POSTHOG_KEY=${NEXT_PUBLIC_POSTHOG_KEY}
      - NEXT_PUBLIC_DISABLE_SIGNUP=${NEXT_PUBLIC_DISABLE_SIGNUP}
      - NEXT_PRIVATE_SIGNING_LOCAL_FILE_PATH=${NEXT_PRIVATE_SIGNING_LOCAL_FILE_PATH:-/opt/documenso/cert.p12}
      - NEXT_PRIVATE_SIGNING_PASSPHRASE=${NEXT_PRIVATE_SIGNING_PASSPHRASE}
    ports:
      - ${PORT:-3000}:${PORT:-3000}
    volumes:
      - /Users/doronkatz/Certs/TPMU/myemail.p12:/opt/documenso/cert.p12

volumes:
  database:
```

Thanks !
