### ISSUE TITLE
Self Hosted Installation, first login, confirmation email never received impossible to use the software

### ISSUE THREAD

**Issue by ralfdigitalagency** [documenso/documenso#1661]
### Issue Description

![Image](https://github.com/user-attachments/assets/d950e531-0f96-4eef-925f-1d4d71460779)

Self Hosted Installation, first login, confirmation email never received impossible to use the software.
Any help?

Thx

### Please check the boxes that apply to this issue report.

- [ ] I have searched the existing issues to make sure this is not a duplicate.
- [ ] I have provided steps to reproduce the issue.
- [ ] I have included relevant environment information.
- [ ] I have included any relevant screenshots.
- [ ] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [ ] I want to work on creating a PR for this issue if approved

**Comment by ralfdigitalagency** [comment]
I followed this suggestions: with NO resolution

https://github.com/documenso/documenso/issues/1307

**Comment by crazyyzarc** [comment]
I don't receive any confirmation e-mails for registration either, but I do receive e-mails to reset my password.

![Image](https://github.com/user-attachments/assets/676baa4a-8d18-42dd-8c92-34cc82c57fb9)

**Comment by crazyyzarc** [comment]
I don't receive any confirmation e-mails for registration either, but I do receive e-mails to reset my passwords.

![Image](https://github.com/user-attachments/assets/3a540c34-0b62-4520-aef1-94555f3bb690)

**Comment by ralfdigitalagency** [comment]
I dont', how you did it? I am stuck now being able to login on the homepage

**Comment by crazyyzarc** [comment]
Show me your docker compose / .env . What's app url and do you have a reverse proxy?

**Comment by ralfdigitalagency** [comment]
https://share.zight.com/nOu42RLd
I use caddy as reverse proxy and Documenso is deployed with Coolify
@crazyyzarc thanks

**Comment by crazyyzarc** [comment]
My 

```
# [[AUTH]]
NEXTAUTH_URL="https://sign.local.intern"
NEXTAUTH_SECRET='gBkdNv4KXNqLkd0lLyCCX1vzdm5thRAb8Z88dX6olxVEUTiElqz4Cmjc'

# [[CRYPTO]]
# Application Key for symmetric encryption and decryption
# REQUIRED: This should be a random string of at least 32 characters
NEXT_PRIVATE_ENCRYPTION_KEY='Gwml3cuvVS9qTdG7WzNmAysZV93gyEJzFNgIQBpZ0xHpoBaxjxh4ZYNb'
# REQUIRED: This should be a random string of at least 32 characters
NEXT_PRIVATE_ENCRYPTION_SECONDARY_KEY='OyJdJifvlSKcr309I4pX0YL7UtYa5EPrK8GhO2CiBamhDhRA3DuyVVcG'

# [[AUTH OPTIONAL]]
# Find documentation on setting up Google OAuth here:
# https://docs.documenso.com/developers/self-hosting/setting-up-oauth-providers#google-oauth-gmail
#NEXT_PRIVATE_GOOGLE_CLIENT_ID=""
#NEXT_PRIVATE_GOOGLE_CLIENT_SECRET=""

# [[URLS]]
NEXT_PUBLIC_WEBAPP_URL="https://sign.local.intern"
NEXT_PUBLIC_MARKETING_URL="https://sign.local.intern"
# URL used by the web app to request itself (e.g. local background jobs)
# This can't be localhost:3000, it doesn't work, you have to use the public URL instead.
NEXT_PRIVATE_INTERNAL_WEBAPP_URL="https://sign.local.intern"

# [[DATABASE]]
NEXT_PRIVATE_DIRECT_DATABASE_URL='postgres://documenso_user:documenso_pw@documenso-db:5432/documenso_db'
NEXT_PRIVATE_DATABASE_URL='postgres://documenso_user:documenso_pw@documenso-db:5432/documenso_db'

POSTGRES_USER='documenso_user'
# This password shouldn't contain special characters like '%', '$' or '@' to avoid issues.
POSTGRES_PASSWORD='documenso_pw'
POSTGRES_DB='documenso_db'

# [[SMTP]]
# OPTIONAL: Defines the transport to use for sending emails. Available options: smtp-auth (default) | smtp-api | mailchannels
NEXT_PRIVATE_SMTP_TRANSPORT="smtp-auth"
# OPTIONAL: Defines the host to use for sending emails.
NEXT_PRIVATE_SMTP_HOST="mail.local.internal"
# OPTIONAL: Defines the port to use for sending emails.
# 465 is not working right now, use STARTTLS on 587 instead
NEXT_PRIVATE_SMTP_PORT=25
# OPTIONAL: Defines the username to use with the SMTP server.
#NEXT_PRIVATE_SMTP_USERNAME=""
# OPTIONAL: Defines the password to use with the SMTP server.
#NEXT_PRIVATE_SMTP_PASSWORD="app-password"
# OPTIONAL: Defines the API key user to use with the SMTP server.
#NEXT_PRIVATE_SMTP_APIKEY_USER=
# OPTIONAL: Defines the API key to use with the SMTP server.
#NEXT_PRIVATE_SMTP_APIKEY=
# OPTIONAL: Defines whether to force the use of TLS.
#TLS is not working right now, set it to "false" and use STARTTLS
NEXT_PRIVATE_SMTP_SECURE="false"
# OPTIONAL: if this is true and NEXT_PRIVATE_SMTP_SECURE is false then TLS is not used even if the server supports STARTTLS extension
NEXT_PRIVATE_SMTP_UNSAFE_IGNORE_TLS="true"
# REQUIRED: Defines the sender name to use for the from address.
NEXT_PRIVATE_SMTP_FROM_NAME="Documenso"
# REQUIRED: Defines the email address to use as the from address.
NEXT_PRIVATE_SMTP_FROM_ADDRESS="notification@test.intern.com"
# OPTIONAL: The API key to use for Resend.com
#NEXT_PRIVATE_RESEND_API_KEY=
# OPTIONAL: The API key to use for MailChannels.
#NEXT_PRIVATE_MAILCHANNELS_API_KEY=
# OPTIONAL: The endpoint to use for the MailChannels API if using a proxy.
#NEXT_PRIVATE_MAILCHANNELS_ENDPOINT=
# OPTIONAL: The domain to use for DKIM signing.
#NEXT_PRIVATE_MAILCHANNELS_DKIM_DOMAIN=
# OPTIONAL: The selector to use for DKIM signing.
#NEXT_PRIVATE_MAILCHANNELS_DKIM_SELECTOR=
# OPTIONAL: The private key to use for DKIM signing.
#NEXT_PRIVATE_MAILCHANNELS_DKIM_PRIVATE_KEY=
# OPTIONAL: Displays the maximum document upload limit to the user in MBs
#NEXT_PUBLIC_DOCUMENT_SIZE_UPLOAD_LIMIT=50
```

**Comment by ralfdigitalagency** [comment]
How can I add/amend those? I installed Coolify and I don't know were to access docker-compose.yml and .env

**Comment by ukthatsawesome** [comment]
Hi @ralfdigitalagency did you find any solution? I am facing the same issue on a newer docker installation for latest image.

**Comment by ralfdigitalagency** [comment]
> Hi [@ralfdigitalagency](https://github.com/ralfdigitalagency) did you find any solution? I am facing the same issue on a newer docker installation for latest image.

No solution so far, nobody came back to me with a solution

**Comment by sanikolaev** [comment]
@ralfdigitalagency I couldn't pinpoint the exact issue, but this was very helpful: https://github.com/documenso/documenso/issues/1167#issuecomment-2422944602. With this setup, I managed to get the email working.

**Comment by emnbdx** [comment]
Hi, i have exactly same issue.

Mail for reset password are sent but not the one for email confirmation

**Comment by Sarmingsteiner** [comment]
> Hi, i have exactly same issue.
> 
> Mail for reset password are sent but not the one for email confirmation

+1

**Comment by ralfdigitalagency** [comment]
> [@ralfdigitalagency](https://github.com/ralfdigitalagency) I couldn't pinpoint the exact issue, but this was very helpful: [#1167 (comment)](https://github.com/documenso/documenso/issues/1167#issuecomment-2422944602). With this setup, I managed to get the email working.

Using those docker-compose.yml and .env will solve my issue too?

**Comment by Sarmingsteiner** [comment]
Update: I removed all the `"` and `'` in the yaml configuration file, and now it works!

**Comment by ralfdigitalagency** [comment]
Still not working I inserted in the env file also the email codes nothing

**Comment by crazyyzarc** [comment]
> Update: I removed all the `"` and `'` in the yaml configuration file, and now it works!

don't work for me :(

**Comment by ukthatsawesome** [comment]
Thank you @sanikolaev this worked for me. I realized couple of things that I updated that worked for me.
1. Comment out the Environment variables you aren't using.
2. Do not use " or ' in .env file.
3. Make sure to have certificate key and file properly set up.
4. Instead of using 587, use 465
5. Keep the NEXT_PRIVATE_SMTP_SECURE and NEXT_PRIVATE_SMTP_UNSAFE_IGNORE_TLS to false.
6. Make sure all the URLS for webapp, internal webapp and marketing url point to the same url.

I will now test if my settings has any issues while using the application. Hopefully, none!

**Comment by crazyyzarc** [comment]
> Thank you [@sanikolaev](https://github.com/sanikolaev) this worked for me. I realized couple of things that I updated that worked for me.
>
>     1. Comment out the Environment variables you aren't using. ✅
>     3. Do not use " or ' in .env file. ✅
>     4. Make sure to have certificate key and file properly set up. (very important) (⚠️ file signing cert is optional, see .env comments)
>     5. Instead of using 465, use 587 ✅
>     6. Keep the NEXT_PRIVATE_SMTP_SECURE and NEXT_PRIVATE_SMTP_UNSAFE_IGNORE_TLS to false. (⚠️ IGNORE_TLS is true, because I use port 25/tcp for smtp)
>     7. Make sure all the URLS for webapp, internal webapp and marketing url point to the same url.> ✅
> I will now test if my settings has any issues while using the application. Hopefully, none!

Same. Only Password reset mails.

![Image](https://github.com/user-attachments/assets/54370e68-e840-4954-9fa5-51233a7763bc)
![Image](https://github.com/user-attachments/assets/e1ad5bcc-b44a-4624-960b-0ede02c8bcaf)

**Comment by crazyyzarc** [comment]
I finally found out. First of all: I use a nginx reverse proxy.
It is important that the internal URLs parameter¹ go to the internal URL (Port 3000) and the public URL goes to the reverse proxy² (443 or whatelse).

¹ NEXT_PRIVATE_INTERNAL_WEBAPP_URL + NEXT_AUTH_URL
² NEXT_PUBLIC_WEBAPP_URL

**Comment by Novapixel1010** [comment]
> Still not working I inserted in the env file also the email codes nothing

Did you ever figure this out?

**Comment by Novapixel1010** [comment]
> > Update: I removed all the `"` and `'` in the yaml configuration file, and now it works!
> 
> also don't work for me :(

Did you ever get this to work

@crazyyzarc

**Comment by Novapixel1010** [comment]
Here is two setups that is working I am using Portainer but this should work via cli too.

# First one

## docker-compse

```yaml
services:
  database:
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER}']
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - database3:/var/lib/postgresql/data

  documenso:
    image: documenso/documenso:latest
    depends_on:
      database:
        condition: service_healthy
    environment:
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXT_PRIVATE_ENCRYPTION_KEY=${NEXT_PRIVATE_ENCRYPTION_KEY}
      - NEXT_PRIVATE_ENCRYPTION_SECONDARY_KEY=${NEXT_PRIVATE_ENCRYPTION_SECONDARY_KEY}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXT_PUBLIC_WEBAPP_URL=${NEXT_PUBLIC_WEBAPP_URL}
      - NEXT_PRIVATE_INTERNAL_WEBAPP_URL=${NEXT_PRIVATE_INTERNAL_WEBAPP_URL}
      - NEXT_PRIVATE_DATABASE_URL=${NEXT_PRIVATE_DATABASE_URL}
      - NEXT_PRIVATE_DIRECT_DATABASE_URL=${NEXT_PRIVATE_DIRECT_DATABASE_URL}
      - NEXT_PUBLIC_UPLOAD_TRANSPORT=${NEXT_PUBLIC_UPLOAD_TRANSPORT}
      - NEXT_PRIVATE_UPLOAD_ENDPOINT=${NEXT_PRIVATE_UPLOAD_ENDPOINT}
      - NEXT_PRIVATE_UPLOAD_FORCE_PATH_STYLE=${NEXT_PRIVATE_UPLOAD_FORCE_PATH_STYLE}
      - NEXT_PRIVATE_UPLOAD_REGION=${NEXT_PRIVATE_UPLOAD_REGION}
      - NEXT_PRIVATE_UPLOAD_BUCKET=${NEXT_PRIVATE_UPLOAD_BUCKET}
      - NEXT_PRIVATE_UPLOAD_ACCESS_KEY_ID=${NEXT_PRIVATE_UPLOAD_ACCESS_KEY_ID}
      - NEXT_PRIVATE_UPLOAD_SECRET_ACCESS_KEY=${NEXT_PRIVATE_UPLOAD_SECRET_ACCESS_KEY}
      - NEXT_PRIVATE_SMTP_TRANSPORT=${NEXT_PRIVATE_SMTP_TRANSPORT}
      - NEXT_PRIVATE_SMTP_HOST=${NEXT_PRIVATE_SMTP_HOST}
      - NEXT_PRIVATE_SMTP_PORT=${NEXT_PRIVATE_SMTP_PORT}
      - NEXT_PRIVATE_SMTP_USERNAME=${NEXT_PRIVATE_SMTP_USERNAME}
      - NEXT_PRIVATE_SMTP_PASSWORD=${NEXT_PRIVATE_SMTP_PASSWORD}
      - NEXT_PRIVATE_SMTP_UNSAFE_IGNORE_TLS=${NEXT_PRIVATE_SMTP_UNSAFE_IGNORE_TLS}
      - NEXT_PRIVATE_SMTP_SECURE=${NEXT_PRIVATE_SMTP_SECURE}
      - NEXT_PRIVATE_SMTP_FROM_NAME=${NEXT_PRIVATE_SMTP_FROM_NAME}
      - NEXT_PRIVATE_SMTP_FROM_ADDRESS=${NEXT_PRIVATE_SMTP_FROM_ADDRESS}
      - NEXT_PRIVATE_SMTP_SERVICE=${NEXT_PRIVATE_SMTP_SERVICE}
      - NEXT_PUBLIC_DOCUMENT_SIZE_UPLOAD_LIMIT=${NEXT_PUBLIC_DOCUMENT_SIZE_UPLOAD_LIMIT}
      - NEXT_PUBLIC_DISABLE_SIGNUP=${NEXT_PUBLIC_DISABLE_SIGNUP}
      - NEXT_PRIVATE_SIGNING_LOCAL_FILE_PATH=${NEXT_PRIVATE_SIGNING_LOCAL_FILE_PATH}
      - NEXT_PRIVATE_SIGNING_PASSPHRASE=${NEXT_PRIVATE_SIGNING_PASSPHRASE}
    ports:
      - ${PORT:-3000}:3000
    volumes:
      - /opt/documenso/cert.p12:/opt/documenso/cert.p12

volumes:
  database3:
```

## .env file

```env
NEXTAUTH_SECRET=EMugJaJ+BKAYgMWJRYRbU8jtvljG89X3W8YhKL2Zcc0=
NEXT_PRIVATE_ENCRYPTION_KEY=EMugJaJ+BKAYgMWJRYRbU8jtvljG89X3W8YhKL2Zcc0=
NEXT_PRIVATE_ENCRYPTION_SECONDARY_KEY=1SzLQ2NKYcmt3yXGo77KE26mdYjKmEjNyQCAlhCfNgA=
NEXT_PRIVATE_SIGNING_PASSPHRASE=novetechlab
NEXTAUTH_URL=https://signing.in.com
NEXT_PUBLIC_WEBAPP_URL=https://signing.in.com
NEXT_PRIVATE_INTERNAL_WEBAPP_URL=http://documenso:3000
NEXT_PRIVATE_DATABASE_URL=postgresql://documenso:changeme@database:5432/documenso
NEXT_PRIVATE_DIRECT_DATABASE_URL=postgresql://documenso:changeme@database:5432/documenso
NEXT_PRIVATE_SMTP_TRANSPORT=smtp-auth
NEXT_PRIVATE_SMTP_HOST=smtp.in.com
NEXT_PRIVATE_SMTP_PORT=1030
NEXT_PRIVATE_SMTP_USERNAME=documenso@in.com
NEXT_PRIVATE_SMTP_PASSWORD=dummy
NEXT_PRIVATE_SMTP_SECURE=false
NEXT_PRIVATE_SMTP_UNSAFE_IGNORE_TLS=true
NEXT_PRIVATE_SMTP_FROM_NAME=Documenso
NEXT_PRIVATE_SMTP_FROM_ADDRESS=documenso@domain.com
NEXT_PUBLIC_UPLOAD_TRANSPORT=database
NEXT_PRIVATE_UPLOAD_ENDPOINT=
NEXT_PRIVATE_UPLOAD_FORCE_PATH_STYLE=
NEXT_PRIVATE_UPLOAD_REGION=
NEXT_PRIVATE_UPLOAD_BUCKET=
NEXT_PRIVATE_UPLOAD_ACCESS_KEY_ID=
NEXT_PRIVATE_UPLOAD_SECRET_ACCESS_KEY=
POSTGRES_USER=documenso
POSTGRES_PASSWORD=changeme
POSTGRES_DB=documenso
PORT=3038
NEXT_PUBLIC_DOCUMENT_SIZE_UPLOAD_LIMIT=10485760
NEXT_PUBLIC_DISABLE_SIGNUP=
NEXT_PRIVATE_SIGNING_LOCAL_FILE_PATH=
```

I use dns server coredns to point `smtp.in.com` to `192.168.1.213` where my mailpit container is

## docker-compose for mailpit

```yaml
services:
  mailpit:
    image: axllent/mailpit

    container_name: mailpit
    restart: unless-stopped
    volumes:
      - ./data:/data
    ports:
      - 8025:8025
      - 1030:1025
      - 1110:1110
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
```

make sure the port you expose for smtp is open. 😆 🤦‍♂  I spent two hours to figure that out. If your debian or ubuntu

```shell
sudo ufw allow 1030
```

**Comment by Novapixel1010** [comment]
# second option

No need to setup dns with this option everything in a single docker-compose

## docker-compose

```yaml
services:
  database:
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER}']
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - database:/var/lib/postgresql/data

  documenso:
    image: documenso/documenso:latest
    depends_on:
      database:
        condition: service_healthy
    environment:
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXT_PRIVATE_ENCRYPTION_KEY=${NEXT_PRIVATE_ENCRYPTION_KEY}
      - NEXT_PRIVATE_ENCRYPTION_SECONDARY_KEY=${NEXT_PRIVATE_ENCRYPTION_SECONDARY_KEY}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXT_PUBLIC_WEBAPP_URL=${NEXT_PUBLIC_WEBAPP_URL}
      - NEXT_PRIVATE_INTERNAL_WEBAPP_URL=${NEXT_PRIVATE_INTERNAL_WEBAPP_URL}
      - NEXT_PRIVATE_DATABASE_URL=${NEXT_PRIVATE_DATABASE_URL}
      - NEXT_PRIVATE_DIRECT_DATABASE_URL=${NEXT_PRIVATE_DIRECT_DATABASE_URL}
      - NEXT_PUBLIC_UPLOAD_TRANSPORT=${NEXT_PUBLIC_UPLOAD_TRANSPORT}
      - NEXT_PRIVATE_UPLOAD_ENDPOINT=${NEXT_PRIVATE_UPLOAD_ENDPOINT}
      - NEXT_PRIVATE_UPLOAD_FORCE_PATH_STYLE=${NEXT_PRIVATE_UPLOAD_FORCE_PATH_STYLE}
      - NEXT_PRIVATE_UPLOAD_REGION=${NEXT_PRIVATE_UPLOAD_REGION}
      - NEXT_PRIVATE_UPLOAD_BUCKET=${NEXT_PRIVATE_UPLOAD_BUCKET}
      - NEXT_PRIVATE_UPLOAD_ACCESS_KEY_ID=${NEXT_PRIVATE_UPLOAD_ACCESS_KEY_ID}
      - NEXT_PRIVATE_UPLOAD_SECRET_ACCESS_KEY=${NEXT_PRIVATE_UPLOAD_SECRET_ACCESS_KEY}
      - NEXT_PRIVATE_SMTP_TRANSPORT=${NEXT_PRIVATE_SMTP_TRANSPORT}
      - NEXT_PRIVATE_SMTP_HOST=${NEXT_PRIVATE_SMTP_HOST}
      - NEXT_PRIVATE_SMTP_PORT=${NEXT_PRIVATE_SMTP_PORT}
      - NEXT_PRIVATE_SMTP_USERNAME=${NEXT_PRIVATE_SMTP_USERNAME}
      - NEXT_PRIVATE_SMTP_PASSWORD=${NEXT_PRIVATE_SMTP_PASSWORD}
      - NEXT_PRIVATE_SMTP_UNSAFE_IGNORE_TLS=${NEXT_PRIVATE_SMTP_UNSAFE_IGNORE_TLS}
      - NEXT_PRIVATE_SMTP_SECURE=${NEXT_PRIVATE_SMTP_SECURE}
      - NEXT_PRIVATE_SMTP_FROM_NAME=${NEXT_PRIVATE_SMTP_FROM_NAME}
      - NEXT_PRIVATE_SMTP_FROM_ADDRESS=${NEXT_PRIVATE_SMTP_FROM_ADDRESS}
      - NEXT_PRIVATE_SMTP_SERVICE=${NEXT_PRIVATE_SMTP_SERVICE}
      - NEXT_PUBLIC_DOCUMENT_SIZE_UPLOAD_LIMIT=${NEXT_PUBLIC_DOCUMENT_SIZE_UPLOAD_LIMIT}
      - NEXT_PUBLIC_DISABLE_SIGNUP=${NEXT_PUBLIC_DISABLE_SIGNUP}
      - NEXT_PRIVATE_SIGNING_LOCAL_FILE_PATH=${NEXT_PRIVATE_SIGNING_LOCAL_FILE_PATH}
      - NEXT_PRIVATE_SIGNING_PASSPHRASE=${NEXT_PRIVATE_SIGNING_PASSPHRASE}
    ports:
      - ${PORT:-3000}:3000
    volumes:
      - /opt/documenso/cert.p12:/opt/documenso/cert.p12

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: unless-stopped
    volumes:
      - ./data:/data
    ports:
      - 8025:8025
      - 1030:1025
      - 1110:1110
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_POP3_AUTH: "john:password-for-email1"

volumes:
  database:
```

## env file

```env
NEXTAUTH_SECRET=EMugJaJ+BKAYgMWJRYRbU8jtvljG89X3W8YhKL2Zcc0=
NEXT_PRIVATE_ENCRYPTION_KEY=EMugJaJ+BKAYgMWJRYRbU8jtvljG89X3W8YhKL2Zcc0=
NEXT_PRIVATE_ENCRYPTION_SECONDARY_KEY=1SzLQ2NKYcmt3yXGo77KE26mdYjKmEjNyQCAlhCfNgA=
NEXT_PRIVATE_SIGNING_PASSPHRASE=novetechlab
NEXTAUTH_URL=https://signing.in.com
NEXT_PUBLIC_WEBAPP_URL=https://signing.in.com
NEXT_PRIVATE_INTERNAL_WEBAPP_URL=http://documenso:3000
NEXT_PRIVATE_DATABASE_URL=postgresql://documenso:changeme@database:5432/documenso
NEXT_PRIVATE_DIRECT_DATABASE_URL=postgresql://documenso:changeme@database:5432/documenso
NEXT_PRIVATE_SMTP_TRANSPORT=smtp-auth
NEXT_PRIVATE_SMTP_HOST=mailpit
NEXT_PRIVATE_SMTP_PORT=1025
NEXT_PRIVATE_SMTP_USERNAME=documenso@in.com
NEXT_PRIVATE_SMTP_PASSWORD=dummy
NEXT_PRIVATE_SMTP_SECURE=false
NEXT_PRIVATE_SMTP_UNSAFE_IGNORE_TLS=true
NEXT_PRIVATE_SMTP_FROM_NAME=Documenso
NEXT_PRIVATE_SMTP_FROM_ADDRESS=documenso@domain.com
NEXT_PUBLIC_UPLOAD_TRANSPORT=database
NEXT_PRIVATE_UPLOAD_ENDPOINT=
NEXT_PRIVATE_UPLOAD_FORCE_PATH_STYLE=
NEXT_PRIVATE_UPLOAD_REGION=
NEXT_PRIVATE_UPLOAD_BUCKET=
NEXT_PRIVATE_UPLOAD_ACCESS_KEY_ID=
NEXT_PRIVATE_UPLOAD_SECRET_ACCESS_KEY=
POSTGRES_USER=documenso
POSTGRES_PASSWORD=changeme
POSTGRES_DB=documenso
PORT=3038
NEXT_PUBLIC_DOCUMENT_SIZE_UPLOAD_LIMIT=10485760
NEXT_PUBLIC_DISABLE_SIGNUP=
NEXT_PRIVATE_SIGNING_LOCAL_FILE_PATH=
```
