### ISSUE TITLE
Documenso on coolify SMTP configuration

### ISSUE THREAD

**Issue by rofkk** [documenso/documenso#1692]
I need help on configuring the SMTP server for my documenso service deployed via coolify.

**Comment by osos** [comment]
I also have troubles getting the SMTP-auth settings to work... however, here on a self-hosted docker solution, trying to setup with smtp host on a another service. 
No debuggin information in log / console, and no connection made.
No sure how to figure this out.

**Comment by Aj7ay7** [comment]
use this in coolify
```
services:
  documenso:
    image: documenso/documenso
    depends_on:
      database:
        condition: service_healthy
    environment:
      - SERVICE_FQDN_DOCUMENSO_3000
      - 'NEXTAUTH_URL=${SERVICE_FQDN_DOCUMENSO_3000}'
      - 'NEXTAUTH_SECRET=${SERVICE_BASE64_AUTHSECRET}'
      - 'NEXT_PRIVATE_ENCRYPTION_KEY=${SERVICE_BASE64_ENCRYPTIONKEY}'
      - 'NEXT_PRIVATE_ENCRYPTION_SECONDARY_KEY=${SERVICE_BASE64_SECONDARYENCRYPTIONKEY}'
      - 'NEXT_PUBLIC_WEBAPP_URL=${SERVICE_FQDN_DOCUMENSO_3000}'
      - 'NEXT_PRIVATE_DATABASE_URL=postgresql://${SERVICE_USER_POSTGRES}:${SERVICE_PASSWORD_POSTGRES}@database/${POSTGRES_DB:-documenso-db}?schema=public'
      - 'NEXT_PRIVATE_DIRECT_DATABASE_URL=postgresql://${SERVICE_USER_POSTGRES}:${SERVICE_PASSWORD_POSTGRES}@database/${POSTGRES_DB:-documenso-db}?schema=public'
      # SMTP Configuration
      - 'NEXT_PRIVATE_SMTP_TRANSPORT=smtp-auth'
      - 'NEXT_PRIVATE_SMTP_HOST=smtp.gmail.com'
      - 'NEXT_PRIVATE_SMTP_PORT=587'
      - 'NEXT_PRIVATE_SMTP_USERNAME=${SMTP_USERNAME}'
      - 'NEXT_PRIVATE_SMTP_PASSWORD=${SMTP_APP_PASSWORD}'
      - 'NEXT_PRIVATE_SMTP_SECURE=false'
      - 'NEXT_PRIVATE_SMTP_FROM_NAME=Documenso'
      - 'NEXT_PRIVATE_SMTP_FROM_ADDRESS=${SMTP_FROM_ADDRESS}'
      - 'NEXT_PUBLIC_DOCUMENT_SIZE_UPLOAD_LIMIT=5'
    healthcheck:
      test:
        - CMD-SHELL
        - "wget -q -O - http://documenso:3000/ | grep -q 'Sign in to your account'"
      interval: 2s
      timeout: 10s
      retries: 20

  database:
    image: 'postgres:16-alpine'
    environment:
      - 'POSTGRES_USER=${SERVICE_USER_POSTGRES}'
      - 'POSTGRES_PASSWORD=${SERVICE_PASSWORD_POSTGRES}'
      - 'POSTGRES_DB=${POSTGRES_DB:-documenso-db}'
    volumes:
      - 'documenso_postgresql_data:/var/lib/postgresql/data'
    healthcheck:
      test:
        - CMD-SHELL
        - 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}'
      interval: 5s
      timeout: 20s
      retries: 10

volumes:
  documenso_postgresql_data: 
```
