### ISSUE TITLE
Reverse Proxy Setup for Self Hosted ENV

### ISSUE THREAD

**Issue by iamdoubz** [documenso/documenso#1718]
### Issue Description

When logging into Documenso, the page redirects users from https://documenso.my.domain to http://localhost:3000 resulting in "Error: No session found".

### Steps to Reproduce

Self host using docker with these compose contents:

<details>
  <summary>Show YAML</summary>

```yml
services:
  database:
    image: postgres:17
    container_name: documenso-db
    hostname: documenso-db
    mem_limit: 512M
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER:?err}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?err}
      - POSTGRES_DB=${POSTGRES_DB:?err}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER}']
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ${CONFIG}/db:/var/lib/postgresql/data

  documenso:
    image: documenso/documenso:undefined
    container_name: documenso
    hostname: documenso
    mem_limit: 2G
    restart: always
    depends_on:
      database:
        condition: service_healthy
    environment:
      - PORT=3000
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:?err}
      - NEXT_PRIVATE_ENCRYPTION_KEY=${NEXT_PRIVATE_ENCRYPTION_KEY:?err}
      - NEXT_PRIVATE_ENCRYPTION_SECONDARY_KEY=${NEXT_PRIVATE_ENCRYPTION_SECONDARY_KEY:?err}
      - NEXT_PRIVATE_GOOGLE_CLIENT_ID=${NEXT_PRIVATE_GOOGLE_CLIENT_ID}
      - NEXT_PRIVATE_GOOGLE_CLIENT_SECRET=${NEXT_PRIVATE_GOOGLE_CLIENT_SECRET}
      - NEXT_PUBLIC_WEBAPP_URL=${NEXT_PUBLIC_WEBAPP_URL:?err}
      - NEXT_PRIVATE_INTERNAL_WEBAPP_URL=${NEXT_PRIVATE_INTERNAL_WEBAPP_URL:-http://localhost:$PORT}
      - NEXT_PRIVATE_DATABASE_URL=${NEXT_PRIVATE_DATABASE_URL:?err}
      - NEXT_PRIVATE_DIRECT_DATABASE_URL=${NEXT_PRIVATE_DIRECT_DATABASE_URL:-${NEXT_PRIVATE_DATABASE_URL}}
      - NEXT_PUBLIC_UPLOAD_TRANSPORT=${NEXT_PUBLIC_UPLOAD_TRANSPORT:-database}
      - NEXT_PRIVATE_UPLOAD_ENDPOINT=${NEXT_PRIVATE_UPLOAD_ENDPOINT}
      - NEXT_PRIVATE_UPLOAD_FORCE_PATH_STYLE=${NEXT_PRIVATE_UPLOAD_FORCE_PATH_STYLE}
      - NEXT_PRIVATE_UPLOAD_REGION=${NEXT_PRIVATE_UPLOAD_REGION}
      - NEXT_PRIVATE_UPLOAD_BUCKET=${NEXT_PRIVATE_UPLOAD_BUCKET}
      - NEXT_PRIVATE_UPLOAD_ACCESS_KEY_ID=${NEXT_PRIVATE_UPLOAD_ACCESS_KEY_ID}
      - NEXT_PRIVATE_UPLOAD_SECRET_ACCESS_KEY=${NEXT_PRIVATE_UPLOAD_SECRET_ACCESS_KEY}
      - NEXT_PRIVATE_SMTP_TRANSPORT=${NEXT_PRIVATE_SMTP_TRANSPORT:?err}
      - NEXT_PRIVATE_SMTP_HOST=${NEXT_PRIVATE_SMTP_HOST}
      - NEXT_PRIVATE_SMTP_PORT=${NEXT_PRIVATE_SMTP_PORT}
      - NEXT_PRIVATE_SMTP_USERNAME=${NEXT_PRIVATE_SMTP_USERNAME}
      - NEXT_PRIVATE_SMTP_PASSWORD=${NEXT_PRIVATE_SMTP_PASSWORD}
      - NEXT_PRIVATE_SMTP_APIKEY_USER=${NEXT_PRIVATE_SMTP_APIKEY_USER}
      - NEXT_PRIVATE_SMTP_APIKEY=${NEXT_PRIVATE_SMTP_APIKEY}
      - NEXT_PRIVATE_SMTP_SECURE=${NEXT_PRIVATE_SMTP_SECURE}
      - NEXT_PRIVATE_SMTP_FROM_NAME=${NEXT_PRIVATE_SMTP_FROM_NAME:?err}
      - NEXT_PRIVATE_SMTP_FROM_ADDRESS=${NEXT_PRIVATE_SMTP_FROM_ADDRESS:?err}
      - NEXT_PRIVATE_SMTP_SERVICE=${NEXT_PRIVATE_SMTP_SERVICE}
      - NEXT_PRIVATE_RESEND_API_KEY=${NEXT_PRIVATE_RESEND_API_KEY}
      - NEXT_PRIVATE_MAILCHANNELS_API_KEY=${NEXT_PRIVATE_MAILCHANNELS_API_KEY}
      - NEXT_PRIVATE_MAILCHANNELS_ENDPOINT=${NEXT_PRIVATE_MAILCHANNELS_ENDPOINT}
      - NEXT_PRIVATE_MAILCHANNELS_DKIM_DOMAIN=${NEXT_PRIVATE_MAILCHANNELS_DKIM_DOMAIN}
      - NEXT_PRIVATE_MAILCHANNELS_DKIM_SELECTOR=${NEXT_PRIVATE_MAILCHANNELS_DKIM_SELECTOR}
      - NEXT_PRIVATE_MAILCHANNELS_DKIM_PRIVATE_KEY=${NEXT_PRIVATE_MAILCHANNELS_DKIM_PRIVATE_KEY}
      - NEXT_PUBLIC_DOCUMENT_SIZE_UPLOAD_LIMIT=${NEXT_PUBLIC_DOCUMENT_SIZE_UPLOAD_LIMIT}
      - NEXT_PUBLIC_POSTHOG_KEY=${NEXT_PUBLIC_POSTHOG_KEY}
      - NEXT_PUBLIC_DISABLE_SIGNUP=${NEXT_PUBLIC_DISABLE_SIGNUP}
      - NEXT_PRIVATE_SIGNING_LOCAL_FILE_PATH=${NEXT_PRIVATE_SIGNING_LOCAL_FILE_PATH:-/opt/documenso/cert.p12}
      - NEXT_PRIVATE_SIGNING_PASSPHRASE=${NEXT_PRIVATE_SIGNING_PASSPHRASE}
    ports:
      - 127.0.0.1:${PORT:-3000}:3000
    volumes:
      - ${CONFIG}/signme.p12:/opt/documenso/cert.p12
```
</details>

And a .env file with these contents:
<details>
  <summary>Show .env</summary>

```
CONFIG=/home/documenso/
PORT=10040
# openssl rand --base64 32
NEXTAUTH_SECRET=KbDayHHOZTVHLGVtuOJ/Tm3tUm4E3hbqIA0uoWKvX1Q=
NEXT_PRIVATE_ENCRYPTION_KEY=KbDayHHOZTVHLGVtuOJ/Tm3tUm4E3hbqIA0uoWKvX1Q=
NEXT_PRIVATE_ENCRYPTION_SECONDARY_KEY=KbDayHHOZTVHLGVtuOJ/Tm3tUm4E3hbqIA0uoWKvX1Q=
NEXT_PRIVATE_GOOGLE_CLIENT_ID=
NEXT_PRIVATE_GOOGLE_CLIENT_SECRET=
NEXT_PRIVATE_OIDC_WELL_KNOWN=
NEXT_PRIVATE_OIDC_CLIENT_ID=
NEXT_PRIVATE_OIDC_CLIENT_SECRET=
NEXT_PRIVATE_OIDC_PROVIDER_LABEL=OIDC
NEXT_PRIVATE_OIDC_SKIP_VERIFY=
NEXT_PUBLIC_WEBAPP_URL=https://documenso.my.domain
NEXT_PUBLIC_MARKETING_URL=https://documenso.my.domain
NEXT_PRIVATE_INTERNAL_WEBAPP_URL=http://documenso:3000
NEXTAUTH_URL=http://documenso:3000
NEXT_AUTH_URL=http://documenso:3000
POSTGRES_USER=documenso
POSTGRES_DB=documenso
POSTGRES_PASSWORD=3QosmwdBbwfJK4Qw2sACgJoUqjsvd
NEXT_PRIVATE_DATABASE_URL=postgres://documenso:3QosmwdBbwfJK4Qw2sACgJoUqjsvd@documenso-db:5432/documenso
NEXT_PRIVATE_DIRECT_DATABASE_URL=postgres://documenso:3QosmwdBbwfJK4Qw2sACgJoUqjsvd@documenso-db:5432/documenso
NEXT_PRIVATE_SIGNING_TRANSPORT=local
NEXT_PRIVATE_SIGNING_PASSPHRASE=YEgqmjhnuehxdxKsut56f/VCUTTiRM/WeyaVOYO52As
NEXT_PRIVATE_SIGNING_LOCAL_FILE_PATH=/opt/documenso/cert.p12
NEXT_PRIVATE_SIGNING_LOCAL_FILE_CONTENTS=
NEXT_PRIVATE_SIGNING_GCLOUD_HSM_KEY_PATH=
NEXT_PRIVATE_SIGNING_GCLOUD_HSM_PUBLIC_CRT_FILE_PATH=
NEXT_PRIVATE_SIGNING_GCLOUD_HSM_PUBLIC_CRT_FILE_CONTENTS=
NEXT_PRIVATE_SIGNING_GCLOUD_APPLICATION_CREDENTIALS_CONTENTS=
NEXT_PUBLIC_UPLOAD_TRANSPORT=database
NEXT_PRIVATE_UPLOAD_ENDPOINT=
NEXT_PRIVATE_UPLOAD_FORCE_PATH_STYLE=
NEXT_PRIVATE_UPLOAD_REGION=
NEXT_PRIVATE_UPLOAD_BUCKET=
NEXT_PRIVATE_UPLOAD_ACCESS_KEY_ID=
NEXT_PRIVATE_UPLOAD_SECRET_ACCESS_KEY=
NEXT_PRIVATE_SMTP_TRANSPORT=smtp-auth
NEXT_PRIVATE_SMTP_HOST=smtp.my.domain
NEXT_PRIVATE_SMTP_PORT=465
NEXT_PRIVATE_SMTP_USERNAME=noreply@documenso.my.domain
NEXT_PRIVATE_SMTP_PASSWORD=k6fbJ4S8qMWcGb0PwC4KU
NEXT_PRIVATE_SMTP_APIKEY_USER=
NEXT_PRIVATE_SMTP_APIKEY=
NEXT_PRIVATE_SMTP_SECURE=true
NEXT_PRIVATE_SMTP_UNSAFE_IGNORE_TLS=
NEXT_PRIVATE_SMTP_FROM_NAME=Documenso Admin
NEXT_PRIVATE_SMTP_FROM_ADDRESS=noreply@documenso.my.domain
NEXT_PRIVATE_SMTP_SERVICE=
NEXT_PRIVATE_RESEND_API_KEY=
NEXT_PRIVATE_MAILCHANNELS_API_KEY=
NEXT_PRIVATE_MAILCHANNELS_ENDPOINT=
NEXT_PRIVATE_MAILCHANNELS_DKIM_DOMAIN=
NEXT_PRIVATE_MAILCHANNELS_DKIM_SELECTOR=
NEXT_PRIVATE_MAILCHANNELS_DKIM_PRIVATE_KEY=
NEXT_PUBLIC_DOCUMENT_SIZE_UPLOAD_LIMIT=42
NEXT_PRIVATE_STRIPE_API_KEY=
NEXT_PRIVATE_STRIPE_WEBHOOK_SECRET=
NEXT_PRIVATE_JOBS_PROVIDER=local
NEXT_PRIVATE_INNGEST_EVENT_KEY=
NEXT_PUBLIC_POSTHOG_KEY=
NEXT_PUBLIC_FEATURE_BILLING_ENABLED=
NEXT_PUBLIC_DISABLE_SIGNUP=
E2E_TEST_AUTHENTICATE_USERNAME=Fake User
E2E_TEST_AUTHENTICATE_USER_EMAIL=fake@mail.com
E2E_TEST_AUTHENTICATE_USER_PASSWORD=notrealpassword
NEXT_PRIVATE_LOGGER_HONEY_BADGER_API_KEY=
```
</details>

### Expected Behavior

Upon clicking the login button, continue to use the public URL and redirect to dashboard.

### Current Behavior

Upon clicking the login button, user is redirected to localhost:3000.

### Operating System [e.g., Windows 10]

Ubuntu 22.04

### Browser [e.g., Chrome, Firefox]

Arc

### Version [e.g., 2.0.1]

[sha256:80e60a16e8edb4e02a423721eee50e00cd3b825b94ae6852646e74c5127e5d35](https://hub.docker.com/layers/documenso/documenso/undefined/images/sha256-6538f7d9b83c4a2c228ed57ffad98650056214294cf245b87e46851c52aa7975)

### Please check the boxes that apply to this issue report.

- [x] I have searched the existing issues to make sure this is not a duplicate.
- [x] I have provided steps to reproduce the issue.
- [x] I have included relevant environment information.
- [ ] I have included any relevant screenshots.
- [x] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [ ] I want to work on creating a PR for this issue if approved

**Comment by MaximeGratens** [comment]
Same for me using docker

**Comment by tutorempire** [comment]
Had the same issue. @dev2adventure 's fix works by adding NEXTAUTH to the yaml and env.

**Comment by iamdoubz** [comment]
I had the correct variable in my .env file, but forgot to add it into the "environment" section in Docker... Once I did that, immediately worked.

So, if anyone else may run into this issue be sure to have the following:

## Simple

### Docker

```yml
  documenso:
    # truncated on purpose...
    environment:
      - PORT=3000
      # ... truncated ...
      - NEXT_PUBLIC_WEBAPP_URL=${NEXT_PUBLIC_WEBAPP_URL:?err}
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:$PORT}
      - NEXT_PRIVATE_INTERNAL_WEBAPP_URL=${NEXT_PRIVATE_INTERNAL_WEBAPP_URL:-http://localhost:$PORT}
```

### Environment file

```
NEXT_PUBLIC_WEBAPP_URL=https://documenso.my.domain
NEXTAUTH_URL=https://documenso.my.domain
NEXT_PRIVATE_INTERNAL_WEBAPP_URL=http://documenso:3000
```

## Complex

### Docker

<details>
  <summary>Show Config</summary>

```yml
services:
  database:
    image: postgres:17
    container_name: documenso-db
    hostname: documenso-db
    mem_limit: 512M
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER:?err}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?err}
      - POSTGRES_DB=${POSTGRES_DB:?err}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER}']
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ${CONFIG}/db:/var/lib/postgresql/data

  documenso:
    image: documenso/documenso:undefined
    container_name: documenso
    hostname: documenso
    mem_limit: 2G
    restart: always
    depends_on:
      database:
        condition: service_healthy
    environment:
      - PORT=3000
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:?err}
      - NEXT_PRIVATE_ENCRYPTION_KEY=${NEXT_PRIVATE_ENCRYPTION_KEY:?err}
      - NEXT_PRIVATE_ENCRYPTION_SECONDARY_KEY=${NEXT_PRIVATE_ENCRYPTION_SECONDARY_KEY:?err}
      - NEXT_PRIVATE_GOOGLE_CLIENT_ID=${NEXT_PRIVATE_GOOGLE_CLIENT_ID}
      - NEXT_PRIVATE_GOOGLE_CLIENT_SECRET=${NEXT_PRIVATE_GOOGLE_CLIENT_SECRET}
      - NEXT_PUBLIC_WEBAPP_URL=${NEXT_PUBLIC_WEBAPP_URL:?err}
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:$PORT}
      - NEXT_PRIVATE_INTERNAL_WEBAPP_URL=${NEXT_PRIVATE_INTERNAL_WEBAPP_URL:-http://localhost:$PORT}
      - NEXT_PRIVATE_DATABASE_URL=${NEXT_PRIVATE_DATABASE_URL:?err}
      - NEXT_PRIVATE_DIRECT_DATABASE_URL=${NEXT_PRIVATE_DIRECT_DATABASE_URL:-${NEXT_PRIVATE_DATABASE_URL}}
      - NEXT_PUBLIC_UPLOAD_TRANSPORT=${NEXT_PUBLIC_UPLOAD_TRANSPORT:-database}
      - NEXT_PRIVATE_UPLOAD_ENDPOINT=${NEXT_PRIVATE_UPLOAD_ENDPOINT}
      - NEXT_PRIVATE_UPLOAD_FORCE_PATH_STYLE=${NEXT_PRIVATE_UPLOAD_FORCE_PATH_STYLE}
      - NEXT_PRIVATE_UPLOAD_REGION=${NEXT_PRIVATE_UPLOAD_REGION}
      - NEXT_PRIVATE_UPLOAD_BUCKET=${NEXT_PRIVATE_UPLOAD_BUCKET}
      - NEXT_PRIVATE_UPLOAD_ACCESS_KEY_ID=${NEXT_PRIVATE_UPLOAD_ACCESS_KEY_ID}
      - NEXT_PRIVATE_UPLOAD_SECRET_ACCESS_KEY=${NEXT_PRIVATE_UPLOAD_SECRET_ACCESS_KEY}
      - NEXT_PRIVATE_SMTP_TRANSPORT=${NEXT_PRIVATE_SMTP_TRANSPORT:?err}
      - NEXT_PRIVATE_SMTP_HOST=${NEXT_PRIVATE_SMTP_HOST}
      - NEXT_PRIVATE_SMTP_PORT=${NEXT_PRIVATE_SMTP_PORT}
      - NEXT_PRIVATE_SMTP_USERNAME=${NEXT_PRIVATE_SMTP_USERNAME}
      - NEXT_PRIVATE_SMTP_PASSWORD=${NEXT_PRIVATE_SMTP_PASSWORD}
      - NEXT_PRIVATE_SMTP_APIKEY_USER=${NEXT_PRIVATE_SMTP_APIKEY_USER}
      - NEXT_PRIVATE_SMTP_APIKEY=${NEXT_PRIVATE_SMTP_APIKEY}
      - NEXT_PRIVATE_SMTP_SECURE=${NEXT_PRIVATE_SMTP_SECURE}
      - NEXT_PRIVATE_SMTP_FROM_NAME=${NEXT_PRIVATE_SMTP_FROM_NAME:?err}
      - NEXT_PRIVATE_SMTP_FROM_ADDRESS=${NEXT_PRIVATE_SMTP_FROM_ADDRESS:?err}
      - NEXT_PRIVATE_SMTP_SERVICE=${NEXT_PRIVATE_SMTP_SERVICE}
      - NEXT_PRIVATE_RESEND_API_KEY=${NEXT_PRIVATE_RESEND_API_KEY}
      - NEXT_PRIVATE_MAILCHANNELS_API_KEY=${NEXT_PRIVATE_MAILCHANNELS_API_KEY}
      - NEXT_PRIVATE_MAILCHANNELS_ENDPOINT=${NEXT_PRIVATE_MAILCHANNELS_ENDPOINT}
      - NEXT_PRIVATE_MAILCHANNELS_DKIM_DOMAIN=${NEXT_PRIVATE_MAILCHANNELS_DKIM_DOMAIN}
      - NEXT_PRIVATE_MAILCHANNELS_DKIM_SELECTOR=${NEXT_PRIVATE_MAILCHANNELS_DKIM_SELECTOR}
      - NEXT_PRIVATE_MAILCHANNELS_DKIM_PRIVATE_KEY=${NEXT_PRIVATE_MAILCHANNELS_DKIM_PRIVATE_KEY}
      - NEXT_PUBLIC_DOCUMENT_SIZE_UPLOAD_LIMIT=${NEXT_PUBLIC_DOCUMENT_SIZE_UPLOAD_LIMIT}
      - NEXT_PUBLIC_POSTHOG_KEY=${NEXT_PUBLIC_POSTHOG_KEY}
      - NEXT_PUBLIC_DISABLE_SIGNUP=${NEXT_PUBLIC_DISABLE_SIGNUP}
      - NEXT_PRIVATE_SIGNING_LOCAL_FILE_PATH=${NEXT_PRIVATE_SIGNING_LOCAL_FILE_PATH:-/opt/documenso/cert.p12}
      - NEXT_PRIVATE_SIGNING_PASSPHRASE=${NEXT_PRIVATE_SIGNING_PASSPHRASE}
    ports:
      - 127.0.0.1:${PORT:-3000}:3000
    volumes:
      - ${CONFIG}/signme.p12:/opt/documenso/cert.p12
```
</details>

### Environment file

<details>
  <summary>Show .env</summary>

```
CONFIG=/home/documenso/
PORT=10040
# openssl rand --base64 32
NEXTAUTH_SECRET=KbDayHHOZTVHLGVtuOJ/Tm3tUm4E3hbqIA0uoWKvX1Q=
NEXT_PRIVATE_ENCRYPTION_KEY=KbDayHHOZTVHLGVtuOJ/Tm3tUm4E3hbqIA0uoWKvX1Q=
NEXT_PRIVATE_ENCRYPTION_SECONDARY_KEY=KbDayHHOZTVHLGVtuOJ/Tm3tUm4E3hbqIA0uoWKvX1Q=
NEXT_PRIVATE_GOOGLE_CLIENT_ID=
NEXT_PRIVATE_GOOGLE_CLIENT_SECRET=
NEXT_PRIVATE_OIDC_WELL_KNOWN=
NEXT_PRIVATE_OIDC_CLIENT_ID=
NEXT_PRIVATE_OIDC_CLIENT_SECRET=
NEXT_PRIVATE_OIDC_PROVIDER_LABEL=OIDC
NEXT_PRIVATE_OIDC_SKIP_VERIFY=
NEXT_PUBLIC_WEBAPP_URL=https://documenso.my.domain
NEXT_PUBLIC_MARKETING_URL=https://documenso.my.domain
NEXT_PRIVATE_INTERNAL_WEBAPP_URL=http://documenso:3000
NEXTAUTH_URL=https://documenso.my.domain
POSTGRES_USER=documenso
POSTGRES_DB=documenso
POSTGRES_PASSWORD=3QosmwdBbwfJK4Qw2sACgJoUqjsvd
NEXT_PRIVATE_DATABASE_URL=postgres://documenso:3QosmwdBbwfJK4Qw2sACgJoUqjsvd@documenso-db:5432/documenso
NEXT_PRIVATE_DIRECT_DATABASE_URL=postgres://documenso:3QosmwdBbwfJK4Qw2sACgJoUqjsvd@documenso-db:5432/documenso
NEXT_PRIVATE_SIGNING_TRANSPORT=local
NEXT_PRIVATE_SIGNING_PASSPHRASE=YEgqmjhnuehxdxKsut56f/VCUTTiRM/WeyaVOYO52As
NEXT_PRIVATE_SIGNING_LOCAL_FILE_PATH=/opt/documenso/cert.p12
NEXT_PRIVATE_SIGNING_LOCAL_FILE_CONTENTS=
NEXT_PRIVATE_SIGNING_GCLOUD_HSM_KEY_PATH=
NEXT_PRIVATE_SIGNING_GCLOUD_HSM_PUBLIC_CRT_FILE_PATH=
NEXT_PRIVATE_SIGNING_GCLOUD_HSM_PUBLIC_CRT_FILE_CONTENTS=
NEXT_PRIVATE_SIGNING_GCLOUD_APPLICATION_CREDENTIALS_CONTENTS=
NEXT_PUBLIC_UPLOAD_TRANSPORT=database
NEXT_PRIVATE_UPLOAD_ENDPOINT=
NEXT_PRIVATE_UPLOAD_FORCE_PATH_STYLE=
NEXT_PRIVATE_UPLOAD_REGION=
NEXT_PRIVATE_UPLOAD_BUCKET=
NEXT_PRIVATE_UPLOAD_ACCESS_KEY_ID=
NEXT_PRIVATE_UPLOAD_SECRET_ACCESS_KEY=
NEXT_PRIVATE_SMTP_TRANSPORT=smtp-auth
NEXT_PRIVATE_SMTP_HOST=smtp.my.domain
NEXT_PRIVATE_SMTP_PORT=465
NEXT_PRIVATE_SMTP_USERNAME=noreply@documenso.my.domain
NEXT_PRIVATE_SMTP_PASSWORD=k6fbJ4S8qMWcGb0PwC4KU
NEXT_PRIVATE_SMTP_APIKEY_USER=
NEXT_PRIVATE_SMTP_APIKEY=
NEXT_PRIVATE_SMTP_SECURE=true
NEXT_PRIVATE_SMTP_UNSAFE_IGNORE_TLS=
NEXT_PRIVATE_SMTP_FROM_NAME=Documenso Admin
NEXT_PRIVATE_SMTP_FROM_ADDRESS=noreply@documenso.my.domain
NEXT_PRIVATE_SMTP_SERVICE=
NEXT_PRIVATE_RESEND_API_KEY=
NEXT_PRIVATE_MAILCHANNELS_API_KEY=
NEXT_PRIVATE_MAILCHANNELS_ENDPOINT=
NEXT_PRIVATE_MAILCHANNELS_DKIM_DOMAIN=
NEXT_PRIVATE_MAILCHANNELS_DKIM_SELECTOR=
NEXT_PRIVATE_MAILCHANNELS_DKIM_PRIVATE_KEY=
NEXT_PUBLIC_DOCUMENT_SIZE_UPLOAD_LIMIT=42
NEXT_PRIVATE_STRIPE_API_KEY=
NEXT_PRIVATE_STRIPE_WEBHOOK_SECRET=
NEXT_PRIVATE_JOBS_PROVIDER=local
NEXT_PRIVATE_INNGEST_EVENT_KEY=
NEXT_PUBLIC_POSTHOG_KEY=
NEXT_PUBLIC_FEATURE_BILLING_ENABLED=
NEXT_PUBLIC_DISABLE_SIGNUP=
E2E_TEST_AUTHENTICATE_USERNAME=Fake User
E2E_TEST_AUTHENTICATE_USER_EMAIL=fake@mail.com
E2E_TEST_AUTHENTICATE_USER_PASSWORD=notrealpassword
NEXT_PRIVATE_LOGGER_HONEY_BADGER_API_KEY=
```
</details>
