### ISSUE TITLE
Initial setup: Docker Compose 'name' attribute causing invalid file issue

### ISSUE THREAD

**Issue by danieltonel** [documenso/documenso#210]
Happens on my initial setup, not sure if it's generally reproducible or just an edge case on my system. When attempting to start my Docker Compose environment using the command npm run d, an error occurs stating:

```
ERROR: The Compose file '././docker/compose-without-app.yml' is invalid because:
'name' does not match any of the regexes: '^x-'
```

## Steps to reproduce
1. Run docker system prune -a to clean the Docker system.
2. Execute npm run d to start the Docker Compose environment.

## Expected result
Docker Compose should start the specified services without any issues.

## Actual result
An error message is shown indicating that the 'name' attribute does not match any of the regexes: '^x-'.

## System information
- Docker version: 20.10.7
- Docker-compose version: 1.29.2
- OS: MacOS 12.6.4

## Proposed solution

The 'name' attribute is not valid in Docker Compose at the top level. We can set the name via an `.env` file in the `/docker` directory. Here's the corrected Docker Compose file:

```yaml
services:
  database:
    image: postgres:15
    container_name: database
    environment:
      - POSTGRES_USER=documenso
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=documenso
    ports:
      - 54320:5432

  inbucket:
    image: inbucket/inbucket
    container_name: mailserver
    ports:
      - 9000:9000
      - 2500:2500
      - 1100:1100
```

`docker/.env`
```
COMPOSE_PROJECT_NAME=documenso
```

or add name tag to docker-compose command:

```
docker-compose -p documenso -f ./docker/compose-without-app.yml up
```
