### ISSUE TITLE
Defaul login and password in docker?

### ISSUE THREAD

**Issue by DeAlexPesh** [documenso/documenso#232]
![image](https://github.com/documenso/documenso/assets/16735261/40e1621c-7d2f-4149-bbe1-4801c0acbffa)

**Comment by Mythie** [comment]
Hey Alex, the default email/password is:

Email: example@documenso.com
Password: 123456789

I noticed we didn't have this in the README so I'll update that to include these details thanks! 😎

**Comment by DeAlexPesh** [comment]
![image](https://github.com/documenso/documenso/assets/16735261/38effbb2-dd82-45cf-bb46-00ca6da750e9)

**Comment by dephraiim** [comment]
Do you have the database running locally/

**Comment by DeAlexPesh** [comment]
> Do you have the database running locally/

```
version: "3"
name: documenso
services:
 documenso:
  image: images/documenso:mode
  container_name: "documenso"
  ports:
   - "0.0.0.0:3000:3000"
  environment:
    - TZ=${TZ}
    - DATABASE_URL=postgres://${DB_USER}:${DB_PASS}@db:5432/${DB_NAME}
    - NEXT_PUBLIC_WEBAPP_URL=${NEXT_PUBLIC_WEBAPP_URL}
    - NEXTAUTH_URL=${NEXTAUTH_URL}
    - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
    - NEXT_PUBLIC_ALLOW_SIGNUP=false
    - NEXT_PUBLIC_ALLOW_SUBSCRIPTIONS=false
    - SMTP_MAIL_HOST=${MAIL_HOST}
    - SMTP_MAIL_PORT=${MAIL_PORT}
    - SMTP_MAIL_USER=${MAIL_USER}
    - SMTP_MAIL_PASSWORD=${MAIL_PASSWORD}
    - MAIL_FROM=${MAIL_FROM}
  depends_on:
   documenso-db:
    condition: service_healthy
  links:
   - documenso-db:db
  networks:
   - documenso
  logging:
   driver: "json-file"
   options:
    max-size: "200k"
    max-file: "5"
  restart: always

 documenso-db:
  image: postgres:15-alpine
  container_name: "documenso-db"
  expose:
   - "5432"
  environment:
   - POSTGRES_USER=${DB_USER}
   - POSTGRES_PASSWORD=${DB_PASS}
   - POSTGRES_DB=${DB_NAME}
   - TZ=${TZ}
   - PGTZ=${TZ}
  volumes: 
   - "/app_base/documenso/db:/var/lib/postgresql/data"
  healthcheck:
   test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER} --quiet" ]
   start_period: 20s
   interval: 30s
   timeout: 10s
   retries: 10
  networks:
   - documenso
  logging:
   driver: "json-file"
   options:
    max-size: "200k"
    max-file: "5"
  restart: always

networks:
 documenso:
  driver: bridge
  name: documenso
```
