### ISSUE TITLE
[DOC-218] Docker Container for Self-Hosting

### ISSUE THREAD

**Issue by ElTimuro** [documenso/documenso#54]
Currently beeing worked on. Feel free to leave feedback or ideas.

<sub>[DOC-218](https://linear.app/documenso/issue/DOC-218/docker-container-for-self-hosting)</sub>

**Comment by treed593** [comment]
From testing:

- Make sure migrations are included to run on container startup
- The application should be able to run behind a Reverse Proxy
    - This could be my lack of experience with NextJS but, after the container starts and I get migrations run I am not able to login with a fresh user because of `code: 'ERR_INVALID_URL'`

**Comment by ElTimuro** [comment]
- @treed593 thanks for the input
- The Error is probably related to next auth, which needs the URL of the application. Did you set that?
- See here for details: https://next-auth.js.org/configuration/options

**Comment by treed593** [comment]
@ElTimuro yes I have that set, here is my docker-compose.

```
version: "3.3"

services:
  database:
    image: postgres:15
    environment:
      - POSTGRES_USER=documenso
      - POSTGRES_PASSWORD=<redacted>
      - POSTGRES_DB=documenso
    ports:
      - 5432:5432

  documenso:
    image: ghcr.io/pennerc/documenso:main
    command: npm run dev
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgres://documenso:<redacted>@database:5432/documenso
      - NEXT_PUBLIC_WEBAPP_URL=https://sign.<redacted>.com
      - NEXTAUTH_SECRET=my-super-secure-secret
      - NEXTAUTH_URL=https://sign.<redacted>.com
      - NEXTAUTH_URL_INTERNAL=http://localhost:3000
      - SENDGRID_API_KEY=
      - SMTP_MAIL_HOST=smtp.gmail.com
      - SMTP_MAIL_PORT=587
      - SMTP_MAIL_USER=<redacted>
      - SMTP_MAIL_PASSWORD=<redacted>
      - MAIL_FROM=<redacted>
      - ALLOW_SIGNUP=true
      - NODE_ENV=production
    ports:
      - 3009:3000
```

I will try again with the updated repo though and see if it works now.
